sudo: required
dist: trusty
language: go
env:
  global:
    - DOKKU_LOCK_PATH=/var/lock/dokku-daemon/dokku-daemon.lock
    - DOKKU_SOCK_PATH=/var/run/dokku-daemon/dokku-daemon.sock
  matrix:
    - DOKKU_VERSION=master
    - DOKKU_VERSION=0.11.2
before_install:
  - sudo -E make setup-travis
install:
  - sudo make -e ci-dependencies install
  - sleep 5
script:
  - make test
